package:
  name: q2-checkm
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  host:
    - python {{ python }}
    - setuptools
    - versioningit
    - wheel
  run:
    - altair <5.0.0
    - dendropy
    - hmmer
    - matplotlib
    - numpy
    - prodigal
    - pysam
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - q2templates >={{ q2templates }}
test:
  requires:
    - parameterized
    - pytest-xdist
  imports:
    - q2_checkm
    - qiime2.plugins.checkm
  commands:
    - pytest --pyargs q2_checkm -n 4
about:
  home: https://github.com/bokulich-lab/q2-checkm
  license: BSD-3-Clause
  license_family: BSD
